import "server-only";

import "./globals.css";
import { createServerClient } from "@/lib/supabase-server";
import { SupabaseListener, SupabaseProvider } from "@/components/client";

// do not cache this layout
export const revalidate = 0;

// metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <head />

      <body className="bg-slate-50">
        <SupabaseProvider session={session}>
          <SupabaseListener serverAccessToken={session?.access_token} />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
